admin_app/urls.py
from django.urls import path
from . import views
app_name='admin_app'


urlpatterns=[
    path('base',views.base,name='base'),
    path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('all_customers/',views.all_customers,name='all_customers'),
    path('add_destination/',views.add_destination,name='add_destination'),
    path('view_destination/',views.view_destination,name='view_destination'),
    path('edit_destination/',views.edit_destination,name='edit_destination'),
    path('add_blog/',views.add_blog,name='add_blog'),
    path('adminView_blog/',views.adminView_blog,name='adminView_blog'),
    path('adminBlog_edit/',views.adminBlog_edit,name='adminBlog_edit'),
    path('view_booking/',views.view_booking,name='view_booking'),
    path('view_queries/',views.view_queries,name='view_queries'),
    path('change_password/',views.change_password,name='change_password'),
]

common/urls.py
from django.urls import path
from . import views
app_name='common'


urlpatterns=[
  
    path('',views.index,name='home'),
    path('view_destinations/', views.view_destinations, name='destinations'),
    path('destination_booking/', views.destination_booking, name='destination_booking'),
    path('blog/',views.blog,name='blog'),
    path('view_blog/',views.view_blog,name='view_blog'),
    path('aboutus',views.aboutus,name='about'),
    path('contactus',views.contactus,name='contact'),
    path('customer_register/',views.customer_register,name='customer_register'),
    path('customer_login/',views.customer_login,name='customer_login'),
    path('my_booking/',views.my_booking,name='my_booking'),
    path('view_profile/',views.view_profile,name='view_profile'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('change_password/',views.change_password,name='change_password'),
    path('customer_logout/',views.customer_logout,name='customer_logout'),
   

    path('admin_register/',views.admin_register,name='admin_register'),
    path('admin_login/',views.admin_login,name='admin_login'),
]

customer_app/urls.py
from django.urls import path
from . import views

app_name='customer_app'

urlpatterns=[
    path('base/',views.base,name='base'),
]

tourism_management_frontend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('customer_app/', include('customer_app.urls')),
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin_app/models.py
from django.db import models

# Create your models here.

common/models.py
from django.db import models

# Create your models here.

customer_app/models.py
from django.db import models

# Create your models here.

admin_app/views.py
from django.shortcuts import render

# Create your views here.

def base(request):
   return render(request,'admin_app_templates/base.html')

def admin_dashboard(request):
   return render(request,'admin_app_templates/admin_dashboard.html')

def all_customers(request):
   return render(request,'admin_app_templates/all_customers.html')

def add_destination(request):
   return render(request,'admin_app_templates/add_destination.html')

def view_destination(request):
   return render(request,'admin_app_templates/view_destination.html')

def edit_destination(request):
   return render(request,'admin_app_templates/edit_destination.html')

def add_blog(request):
   return render(request,'admin_app_templates/add_blog.html')

def adminView_blog(request):
   return render(request,'admin_app_templates/adminView_blog.html')


def adminBlog_edit(request):
   return render(request,'admin_app_templates/adminBlog_edit.html')

def view_booking(request):
   return render(request,'admin_app_templates/view_booking.html')

def view_queries(request):
   return render(request,'admin_app_templates/view_queries.html')

def change_password(request):
   return render(request,'admin_app_templates/change_password.html')

common/views.py
from django.shortcuts import render

# Create your views here.

def base(request):
   
    return render(request,'common_templates/base.html')

def index(request):
   
    return render(request,'common_templates/index.html')

def view_destinations(request):
   
    return render(request,'common_templates/view_destinations.html')

def destination_booking(request):
   return render(request,'common_templates/destination_booking.html')

def blog(request):
   
    return render(request,'common_templates/blog.html')

def view_blog(request):
   
    return render(request,'common_templates/view_blog.html')

def aboutus(request):
   
    return render(request,'common_templates/aboutus.html')

def contactus(request):
   
    return render(request,'common_templates/contactus.html')


def customer_register(request):
   
    return render(request,'common_templates/customer_register.html')

def customer_login(request):
   
    return render(request,'common_templates/customer_login.html')


def my_booking(request):
   
    return render(request,'common_templates/my_booking.html')

def view_profile(request):
   
    return render(request,'common_templates/view_profile.html')

def edit_profile(request):
   
    return render(request,'common_templates/edit_profile.html')


def change_password(request):
   
    return render(request,'common_templates/change_password.html')

def customer_logout(request):
   
    return render(request,'common_templates/customer_logout.html')
# /////////////// ADMIN //////////////////////

def admin_register(request):
   
    return render(request,'common_templates/admin_register.html')


def admin_login(request):
   
    return render(request,'common_templates/admin_login.html')

customer_app/views.py
from django.shortcuts import render

# Create your views here.


def base(request):
    return render(request,'customer_app_templates/base.html')

admin_app/templates/admin_app_templates/add_blog.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>

<style>
    .alert-success {
        display: none;
    }
</style>

{% endblock %}

{% block title %}Add Blog{% endblock %}
{% block content %}



<section>
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-9">

                <h1 class="mb-4 mt-5">Add Blog</h1>

                <div class="card shadow-lg p-3 mb-5 bg-white rounded" style="border-radius: 15px;">
                    <div class="card-body">

                        <div class="row align-items-center pt-4 pb-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Topic</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="text" placeholder="Topic" id="topic" class="form-control form-control-lg"
                                    required />

                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Post Date</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="date" class="form-control form-control-lg" id="date" placeholder="Date"
                                    required />

                            </div>
                        </div>
                        <hr class="mx-n3">
                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Description</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <textarea class="form-control" rows="3" id="description"
                                    placeholder="Right description..." required></textarea>

                            </div>
                        </div>

                        <hr class="mx-n3">
                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">

                                <h6 class="mb-0">Upload Image</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input class="form-control form-control-lg" id="image" type="file" required />
                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="px-5 py-4">
                            <button type="button" id="subBtn" class="btn btn-primary btn-lg">Add Blog</button>
                        </div>
                        <!-- <span id="span1"></span> -->
                        <div class="alert alert-success alert-dismissible" id="alert-success">
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            <strong id="span1"></strong>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>



<script>

    $(document).ready(function () {
        $('#subBtn').click(function () {
            var blog_data = new FormData();
            blog_data.append('Blog_topic', $('#topic').val());
            blog_data.append('post_date', $('#date').val());
            blog_data.append('blog_description', $('#description').val());
            blog_data.append('blog_image', $('#image')[0].files[0]);
            console.log(blog_data)

            $.ajax({
                url: "http://localhost:9000/admin_app/add_blog/",
                data: blog_data,
                type: 'POST',
                contentType: false,
                processData: false,
                success: function (response) {
                    if (response.message) {
                        $('#span1').html(response.message);
                        $('#alert-success').show();
                    } else {
                        $('#alert-success').hide();
                    }
                    $('#topic').val('')
                    $('#date').val('')
                    $('#description').val('')
                    $('#image').val('')



                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            })
        })
    })


</script>



{% endblock %}

admin_app/templates/admin_app_templates/adminBlog_edit.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>

<style>
    .alert-success {
        display: none;
    }
</style>

{% endblock %}

{% block title %}Edit Blog{% endblock %}
{% block content %}



<section>
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-9">

                <h1 class="mb-4 mt-5">Add Blog</h1>

                <div class="card shadow-lg p-3 mb-5 bg-white rounded" style="border-radius: 15px;">
                    <div class="card-body">
                        <form id="blogForm" enctype="multipart/form-data">
                            <div class="row align-items-center pt-4 pb-3">
                                <div class="col-md-3 ps-5">

                                    <h6 class="mb-0">Topic</h6>

                                </div>
                                <div class="col-md-9 pe-5">

                                    <input type="text" placeholder="Topic" id="topic"
                                        class="form-control form-control-lg" required />

                                </div>
                            </div>

                            <hr class="mx-n3">

                            <div class="row align-items-center py-3">
                                <div class="col-md-3 ps-5">

                                    <h6 class="mb-0">Post Date</h6>

                                </div>
                                <div class="col-md-9 pe-5">

                                    <input type="date" class="form-control form-control-lg" id="date" placeholder="Date"
                                        required />

                                </div>
                            </div>
                            <hr class="mx-n3">
                            <div class="row align-items-center py-3">
                                <div class="col-md-3 ps-5">

                                    <h6 class="mb-0">Description</h6>

                                </div>
                                <div class="col-md-9 pe-5">

                                    <textarea class="form-control description" rows="3" id="description"
                                        placeholder="Right description..." required></textarea>

                                </div>
                            </div>

                            <hr class="mx-n3">
                            <div class="row align-items-center py-3">
                                <div class="col-md-3 ps-5">

                                    <h6 class="mb-0" id="image-label">Upload Image</h6>

                                </div>
                                <div class="col-md-9 pe-5">

                                    <input class="form-control form-control-lg" id="image" type="file" required />
                                </div>
                                <span id="show_img"></span>
                                <div>
                                    <img src="" id="myimage"
                                        style="width: 30px;width: 177px;margin-top: 15px;    height: 120px;" alt="">
                                </div>
                            </div>

                            <hr class="mx-n3">

                            <div class="px-5 py-4">
                                <button type="button" id="subBtn" class="btn btn-success btn-lg mt-3">Update
                                    Blog</button>
                                <button class="btn btn-info btn-lg mt-3"><a style="text-decoration: none; color: #fff;"
                                        href="{% url 'admin_app:adminView_blog' %}">Back</a></button>


                            </div>

                            <!-- <span id="span1"></span> -->
                            <div class="alert alert-success alert-dismissible" id="alert-success">
                                <button type="button" id="subBtn" class="btn-close" data-bs-dismiss="alert"></button>
                                <strong id="span1"></strong>
                            </div>

                        </form>



                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

<script>
    $(document).ready(function () {
        // Get the ID from the URL
        var urlParams = new URLSearchParams(window.location.search);
        var blogId = urlParams.get('id');

        // Make an AJAX GET request to fetch the blog data
        $.ajax({
            url: "http://localhost:9000/admin_app/update_blog/" + blogId + "/",
            type: "GET",
            success: function (data) {
                // Populate the fields with the fetched data
                $("#topic").val(data.Blog_topic);
                $("#date").val(data.post_date);
                $("#description").val(data.blog_description)
                // console.log(data.blog_description)
                img = 'http://127.0.0.1:9000' + data.blog_image
                $("#myimage").attr('src', img);
                // console.log(data.blog_image)

            },
            error: function (xhr, errmsg, err) {
                console.log(xhr.status + ": " + xhr.responseText);
            }
        });

        // Handle form submission
        $("#subBtn").click(function () {
            var form_data = new FormData();
            form_data.append('id', blogId);

            // Check if the topic field should be updated
            if ($("#topic").val() !== "") {
                form_data.append('Blog_topic', $("#topic").val());
            }

            // Check if the post_date field should be updated
            if ($("#date").val() !== "") {
                form_data.append('post_date', $("#date").val());
            }

            // Check if the blog_description field should be updated
            if ($("#description").val() !== "") {
                form_data.append('blog_description', $("#description").val());
            }

            // Check if a new image is added to the input field
            if ($('#image')[0].files.length > 0) {
                form_data.append('blog_image', $('#image')[0].files[0]);
            }
            console.log(form_data)
            $.ajax({
                url: "http://localhost:9000/admin_app/update_blog/" + blogId + "/",
                type: "PUT",
                data: form_data,
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log(data)
                    if (data.message) {
                        $('#span1').html(data.message);
                        $('#alert-success').show();
                        window.location.href = "http://127.0.0.1:8001/admin_app/adminView_blog/";
                    } else {
                        $('#alert-success').hide();
                    }
                },
                error: function (xhr, errmsg, err) {
                    console.log(xhr.status + ": " + xhr.responseText);
                }
            });
        });
    });
</script>


{% endblock %}

admin_app/templates/admin_app_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- icon link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>





    <!-- jquery cdn -->
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

    <style>
        body {
            font-family: 'Poppins', sans-serif;
            color: black;
        }

        #navbar {
            box-shadow: 0 3px 9px 3px rgba(0, 0, 0, 0.1);
            position: sticky;
            top: 0;
            z-index: 1;
            padding: .5rem .5rem;

        }

        .koko {
            font-size: 20px;
            color: rgba(165, 42, 42, 0.938);

        }

        .dropdown:hover .dropdown-menu {
            display: block;
        }

        #navbarNav a {
            border-bottom: 2px solid transparent;
            color: black;

        }

        #navbarNav a:hover {
            border-bottom: 2px solid rgba(165, 42, 42, 0.938);
            color: black;

        }

        #navbarNav i:hover {
            color: rgba(165, 42, 42, 0.938);


        }

        #admin_name {
            display: inline-block;
        }

        #admin_name::first-letter {
            text-transform: uppercase;
        }

        footer {
            background-color: #e9ebed !important;
        }
    </style>
    {% block header %}

    {% endblock %}
    <title>{% block title %}base{% endblock %}</title>
</head>

<body>

    <body id="ll">
        <!-- navbar -->
        <nav class="navbar navbar-expand-lg bg-light " id="navbar">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold fs-2" href="#"><span class="koko">Tourism Management</span> </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-expanded="false">
                    <span class="navbar-toggler-icon "><i class="bi bi-list"></i></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarNav">
                    <ul class="navbar-nav fw-bold mx-auto" id="list">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'admin_app:admin_dashboard' %}"
                                style="color: brown;">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_app:all_customers' %}" style="color: black;">All
                                User</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="blogDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Blog
                            </a>
                            <div class="dropdown-menu" aria-labelledby="blogDropdown">
                                <a class="dropdown-item" href="{% url 'admin_app:add_blog' %}">Add Blog</a>
                                <a class="dropdown-item" href="{% url 'admin_app:adminView_blog' %}">View Blog</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="blogDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Destination
                            </a>
                            <div class="dropdown-menu" aria-labelledby="blogDropdown">
                                <a class="dropdown-item" href="{% url 'admin_app:add_destination' %}">Add
                                    Destination</a>
                                <a class="dropdown-item" href="{% url 'admin_app:view_destination' %}">View
                                    Destination</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="" style="color: black;">View Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_app:change_password' %}"
                                style="color: black;">Change Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_app:view_queries' %}" style="color: black;">View
                                Contact</a>
                        </li>


                        <!-- <li class="nav-item ms-5">
                            <form class="d-flex" method="">

                                <input class="form-control me-2 " type="search" placeholder="Search product"
                                    aria-label="Search" id="searchdata" name="searchdata">
                                <button class="btn btn-outline-dark" type="type" id="searchbtn"
                                    style="background-color: rgb(189, 68, 68);color: white;"><i
                                        class="bi bi-search"></i></button>

                            </form>
                            <div class="serch" id="search">

                               
                            </div>
                        </li> -->

                    </ul>

                    <div class="ms-3">
                        <h5 class="nav-link"
                            style="font-size: 15px; margin: auto;font-weight: bold;background-color: lavender;">Welcome
                            <span id="admin_name"></span>
                        </h5>

                    </div>

                    <div class="ms-3 ">
                        <a href="" type="button" id="logout" class="btn"><i class="bi bi-person-fill">Logout</i></a>
                    </div>
                </div>
            </div>
            </div>
        </nav>


        {% block content %}{% endblock %}



        <footer class="mt-5 pt-5 pb-3" id="footer">
            <div class="container text-center text-md-start">
                <div class="row ">
                    <div class="col-lg-4 col-md-4 col-sm-6">
                        <h5><span class="koko">Tourism Management</h5>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ducimus, unde? Et, facere?
                            Distinctio officia, pariatur eos ipsa tenetur veniam sapiente! Aut ipsam dicta, numquam
                            repudiandae natus expedita alias deserunt. Quam?</p>
                    </div>
                    <!-- <div class="col-lg-3 col-md-3 col-sm-6">
                                <h5>PRODUCTS</h5>
                                <p><a href=""></a>Dates</p>
                                <p><a href=""></a>Dry Fruit</p>
                                <p><a href=""></a>Chocolates</p>
                                <p><a href=""></a>Nuts</p>
                            </div> -->
                    <div class="col-lg-4 col-md-4 col-sm-6">
                        <h5>LINKS</h5>
                        <p><a href=""></a>Home</p>
                        <p><a href=""></a>Blog</p>
                        <p><a href=""></a>About Us</p>
                        <p><a href=""></a>Contact Us</p>
                        <p><a href=""></a>Terms & Conditions</p>

                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6">
                        <h5>CONTACT</h5>
                        <p><i class="bi bi-house-fill"></i> Calicut,kerala</p>
                        <p><i class="bi bi-envelope-fill"></i>tourism@gmail.com</p>
                        <p><i class="bi bi-phone-fill"></i>+91 9645312745</p>
                        <p><i class="bi bi-printer-fill"></i>+33 2123215</p>

                    </div>

                </div>
                <hr class="mb-4">
                <div class="row">
                    <div class="col-lg-7 col-sm-12">
                        <p>copyright 2020 reserved by:<strong>Tourism management</strong></p>
                    </div>
                    <div class="col-lg-4 col-sm-12">
                        <ul class="list-unstyled list-inline">
                            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i
                                        class="bi bi-facebook"></i></a></li>
                            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i
                                        class="bi bi-whatsapp"></i></a></li>

                            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i
                                        class="bi bi-twitter"></i></a></li>

                            <li class="list-inline-item"><a href="" class="btn-sm" style="font-size: 25px;"><i
                                        class="bi bi-linkedin"></i></a></li>

                        </ul>
                    </div>
                </div>
            </div>
        </footer>



    </body>




    </script>
    <script rel="stylesheet" href="{% static '/bootstrap/bootstrap.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

    <script>
        $(document).ready(function () {
            var token = localStorage.getItem('token');
            var admin_id = localStorage.getItem('admin_id');
            // console.log(admin_id)
            // console.log(token)
            $.ajax({
                url: 'http://localhost:9000/admin_app/admin_name/' + admin_id + '/',
                type: 'GET',
                headers: {
                    'Authorization': 'Token ' + token
                },
                success: function (response) {
                    
                    var adminName = response.admin_data.admin_name;
                    
                    $('#admin_name').text(adminName)


                }
            })



            // var admin_id = localStorage.getItem('admin_id');
            // console.log(admin_id, 'hi');

            // if (admin_id !== null) {
            //     var token = localStorage.getItem('token');
            //     console.log(token, 'hello');

            //     $.ajax({
            //         url: 'http://localhost:9000/admin_app/admin_name/' + admin_id + '/',
            //         type: 'GET',
            //         headers: {
            //             'Authorization': 'Token ' + token
            //         },
            //         success: function (response) {
            //             console.log(response, 'hello');
            //             var adminName = response.admin_data;
            //             console.log(adminName);
            //             $('#admin_name').text(adminName);
            //         }
            //     });
            // }



        })
    </script>



</html>